plugins {
    id 'com.android.application'
    id 'com.android.legacy-kapt'
}

android {
    namespace 'com.lucian.myclock'
    compileSdk 37

    defaultConfig {
        applicationId "com.lucian.myclock"
        minSdk 29
        targetSdk 37
        versionCode 20260828
        versionName "1.5_by_LucianLu"
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        }
    }

    dataBinding {
        enabled true
    }

    buildFeatures {
        buildConfig true
    }

    bundle {
        storeArchive {
            enable = false
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}