name: Android CI

on:
  push:
    branches: [  master  ]

  pull_request:
    branches: [  master  ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
    - uses: actions/checkout@v2

    - name: Setup android env
      run: npx envinfo
  
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile apk
      run: ./gradlew assembleDebug

    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/

# [TODO] Need to sign key for release version
#    - name: Compile release apk
#      run: ./gradlew assembleRelease

#    - name: Upload release apk
#      uses: actions/upload-artifact@v2
#      with:
#          name: app-release.apk
#          path: app/build/outputs/apk/release/

    - name: Compile aab
      run: ./gradlew bundleDebug

    - name: Upload aab
      uses: actions/upload-artifact@v2
      with:
          name: app-debug.aab
          path: app/build/outputs/bundle/debug/

# [TODO] Need to sign key for release version
#    - name: Compile release aab
#      run: ./gradlew bundleRelease

#    - name: Upload release aab
#      uses: actions/upload-artifact@v2
#      with:
#          name: app-release.aab
#          path: app/build/outputs/bundle/release/
