name: Android CI

on:
  push:
    branches: [  master  ]

  pull_request:
    branches: [  master  ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Envinfo
      run: npx envinfo
  
    - name: Build application
      run: |
        yarn install && cd android && chmod +x gradlew && ./gradlew build bundleRelease 
        du -shc `find . -regex '.+\.\(apk\|aab\)$'`
      
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  
    - name: Upload aab
      uses: actions/upload-artifact@v2
      with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/
