name: Android CI

on:
  push:
    branches: [  master  ]

  pull_request:
    branches: [  master  ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Envinfo
      run: npx envinfo
  
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Compile
      run: ./gradlew assembleRelease

    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
          name: app-release.apk
          path: app/build/outputs/apk/release/
  
    - name: Upload aab
      uses: actions/upload-artifact@v2
      with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/
